version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: termserver
      POSTGRES_USER: termserver
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U termserver"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: